apiVersion: v2
name: knit-db-postgres
description: knitfab database (postgres)
type: application
keywords:
  - knitfab
  - MLOps
  - Lineage Tracking
  - Workflow
  - Tag Based Workflow

version: v1.1.0-patch
appVersion: v1.1.0-patch-c334736
